// components/Counter/Counter.component.tsx
'use client';

import { Button, Group, Stack, Text } from '@mantine/core';
import { useCounterStore } from './Counter.component.state';

export function Counter() {
  const { count, increment, decrement } = useCounterStore();
  return (
    <Group justify="flex-start" align="center" gap="xs">
      <Text className="bg-red-100" size="md">
        {count}
      </Text>
      <Button size="sm" variant="outline" onClick={decrement}>
        -
      </Button>
      <Button size="sm" variant="outline" onClick={increment}>
        +
      </Button>
    </Group>
  );
}

// src/posts/Counter.svelte
<script>
	import counterStore from './Counter.store';
</script>

<div class="flex items-center justify-center space-x-4">
	<button
		onclick={counterStore.decrement}
		class="rounded bg-red-500 px-4 py-2 font-bold text-white hover:bg-red-700">-</button
	>
	<span>{$counterStore}</span>
	<button
		onclick={counterStore.increment}
		class="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700">+</button
	>
</div>
